services:
  redis:
    image: redis:7.2.3-alpine
    container_name: test-das-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - das-network

  mongodb:
    image: mongo:latest
    container_name: test-das-mongodb
    restart: always
    attach: false
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          'db.runCommand("ping").ok',
          "|",
          "mongo",
          "das-mongo:27017/test",
          "--quiet",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - das-network

  metta-parser:
    image: trueagi/das:0.5.4-metta-parser
    container_name: test-das-metta-parser
    working_dir: /opt/das-metta-parser
    command: db_loader /tmp/animals.metta
    volumes:
      - /tmp/das-builder:/tmp
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: mongodb
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: redis
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
      DAS_DATABASE_USERNAME: root
      DAS_DATABASE_PASSWORD: root
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - das-network

  das-attention-broker:
    working_dir: /opt
    image: das-builder:latest
    container_name: test-das-attention-broker
    command: ./bin/attention_broker_service 37007
    ports:
      - 37007:37007
    volumes:
      - ./src:/opt
    depends_on:
      - mongodb
      - redis
      - metta-parser
    restart: on-failure
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: mongodb
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: redis
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
    networks:
      - das-network

  das-query-agent:
    working_dir: /opt
    image: das-builder:latest
    container_name: test-das-query-agent-node
    command: ./bin/query_broker 35700
    ports:
      - 35700:35700
    volumes:
      - ./src:/opt
    restart: on-failure
    depends_on:
      - mongodb
      - redis
      - metta-parser
      - das-attention-broker
    environment:
      ATTENTION_BROKER_HOSTNAME: das-attention-broker
      ATTENTION_BROKER_PORT: 37007
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: mongodb
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: redis
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
    networks:
      - das-network

  das-link-create-agent:
    image: das-builder:latest
    container_name: test-das-link-create-agent-node
    working_dir: /opt
    command: ./bin/link_creation_server --type server --config_file /tmp/link.config
    volumes:
      - /tmp/das-builder:/tmp
      - ./src:/opt
    ports:
      - 9090:9090
    restart: on-failure
    depends_on:
      - mongodb
      - redis
      - metta-parser
      - das-attention-broker
      - das-query-agent
    networks:
      - das-network

networks:
  das-network:
    driver: bridge
