name: Build Mork Server and Loader Images

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-mork-images:
    strategy:
      matrix:
        platforms: [amd64, arm64]
    runs-on:
      - self-hosted
      - ${{ matrix.platforms }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Mork Server Image (native)
        run: |
          docker build \
            -t trueagi/das:mork-server-${{ matrix.platforms }}-${{ inputs.version }} \
            -f src/docker/mork/Dockerfile.server .

      - name: Build Mork Loader Image (native)
        run: |
          docker build \
            -t trueagi/das:mork-loader-${{ matrix.platforms }}-${{ inputs.version }} \
            -f src/docker/mork/Dockerfile.loader .

      - name: Push Mork Server Image
        run: docker push trueagi/das:mork-server-${{ matrix.platforms }}-${{ inputs.version }}

      - name: Push Mork Loader Image
        run: docker push trueagi/das:mork-loader-${{ matrix.platforms }}-${{ inputs.version }}

  publish-manifests:
    needs: build-mork-images
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push Mork Server manifest
        run: |
          docker manifest create trueagi/das:mork-server-${{ inputs.version }} \
            --amend trueagi/das:mork-server-amd64-${{ inputs.version }} \
            --amend trueagi/das:mork-server-arm64-${{ inputs.version }}

          docker manifest push trueagi/das:mork-server-${{ inputs.version }}

      - name: Create and push Mork Loader manifest
        run: |
          docker manifest create trueagi/das:mork-loader-${{ inputs.version }} \
            --amend trueagi/das:mork-loader-amd64-${{ inputs.version }} \
            --amend trueagi/das:mork-loader-arm64-${{ inputs.version }}

          docker manifest push trueagi/das:mork-loader-${{ inputs.version }}
