name: Build Mork Server and Loader Images

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      server_image:
        required: true
        type: string
      loader_image:
        required: true
        type: string
      server_dockerfile:
        required: true
        type: string
      loader_dockerfile:
        required: true
        type: string

jobs:
  build-mork-images:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export inputs to env
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "MORK_SERVER_IMAGE=${{ inputs.server_image }}" >> $GITHUB_ENV
          echo "MORK_LOADER_IMAGE=${{ inputs.loader_image }}" >> $GITHUB_ENV
          echo "MORK_SERVER_DOCKERFILE=${{ inputs.server_dockerfile }}" >> $GITHUB_ENV
          echo "MORK_LOADER_DOCKERFILE=${{ inputs.loader_dockerfile }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Mork Server Image
        run: |
          docker buildx build \
            -t ${MORK_SERVER_IMAGE}-${VERSION} \
            --load \
            -f ${MORK_SERVER_DOCKERFILE} .

      - name: Build Mork Loader Image
        run: |
          docker buildx build \
            -t ${MORK_LOADER_IMAGE}-${VERSION} \
            --load \
            -f ${MORK_LOADER_DOCKERFILE} .

      - name: Push Mork Server Image
        run: docker push ${MORK_SERVER_IMAGE}-${VERSION}

      - name: Push Mork Loader Image
        run: docker push ${MORK_LOADER_IMAGE}-${VERSION}
